/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GBIFOccurrence } from "../types";

/**
 * High-quality, realistic Indonesian biodiversity occurrence datasets
 * to serve as pre-baked samples for the Biblioshiny-style CSV platform.
 */

// --- 1. HARIMAU SUMATRA (Panthera tigris sumatrae) ---
export const SAMPLE_HARIMAU_SUMATRA: GBIFOccurrence[] = [
  // Aceh (Leuser)
  {
    key: 101,
    scientificName: "Panthera tigris sumatrae Pocock, 1929",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "MAMMALIA",
    order: "CARNIVORA",
    family: "FELIDAE",
    genus: "Panthera",
    decimalLatitude: 3.7542,
    decimalLongitude: 97.4321,
    year: 2024,
    month: 5,
    day: 12,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "MACHINE_OBSERVATION", // Camera trap
    recordedBy: "TN Gunung Leuser Patrol Unit",
    locality: "Kawasan Inti Taman Nasional Gunung Leuser, Aceh Tenggara",
    eventDate: "2024-05-12",
    institutionCode: "TNGLa",
  },
  {
    key: 102,
    scientificName: "Panthera tigris sumatrae Pocock, 1929",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "MAMMALIA",
    order: "CARNIVORA",
    family: "FELIDAE",
    genus: "Panthera",
    decimalLatitude: 3.6120,
    decimalLongitude: 97.6540,
    year: 2023,
    month: 8,
    day: 24,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "HUMAN_OBSERVATION", // Footprint / pugmark
    recordedBy: "WCS Indonesia Team",
    locality: "Sektor Singkil Baru, Aceh Singkil",
    eventDate: "2023-08-24",
    institutionCode: "WCS-ID",
  },
  {
    key: 103,
    scientificName: "Panthera tigris sumatrae Pocock, 1929",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "MAMMALIA",
    order: "CARNIVORA",
    family: "FELIDAE",
    genus: "Panthera",
    decimalLatitude: 4.1201,
    decimalLongitude: 97.2204,
    year: 2021,
    month: 11,
    day: 5,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "PRESERVED_SPECIMEN",
    recordedBy: "Museum Zoologicum Bogoriense",
    locality: "Blangkejeren, Gayo Lues",
    eventDate: "2021-11-05",
    institutionCode: "MZB",
  },
  {
    key: 104,
    scientificName: "Panthera tigris sumatrae Pocock, 1929",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "MAMMALIA",
    order: "CARNIVORA",
    family: "FELIDAE",
    genus: "Panthera",
    decimalLatitude: 3.2501,
    decimalLongitude: 97.9042,
    year: 2025,
    month: 2,
    day: 18,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "MACHINE_OBSERVATION",
    recordedBy: "Forum Konservasi Leuser (FKL)",
    locality: "Kawasan Hutan Lindung Subulussalam",
    eventDate: "2025-02-18",
    institutionCode: "FKL-ID",
  },
  // North Sumatra (Batang Toru / Bukit Barisan)
  {
    key: 105,
    scientificName: "Panthera tigris sumatrae Pocock, 1929",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "MAMMALIA",
    order: "CARNIVORA",
    family: "FELIDAE",
    genus: "Panthera",
    decimalLatitude: 1.6234,
    decimalLongitude: 99.1205,
    year: 2022,
    month: 4,
    day: 9,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "HUMAN_OBSERVATION",
    recordedBy: "Masyarakat Mitra Polhut (MMP)",
    locality: "Hutan Batang Toru, Tapanuli Selatan",
    eventDate: "2022-04-09",
    institutionCode: "BKSDA-SU",
  },
  {
    key: 106,
    scientificName: "Panthera tigris sumatrae Pocock, 1929",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "MAMMALIA",
    order: "CARNIVORA",
    family: "FELIDAE",
    genus: "Panthera",
    decimalLatitude: 1.8842,
    decimalLongitude: 98.9870,
    year: 2020,
    month: 10,
    day: 14,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "MACHINE_OBSERVATION",
    recordedBy: "Sumatran Tiger Ranger",
    locality: "Suaka Margasatwa Barumun, Padang Lawas",
    eventDate: "2020-10-14",
    institutionCode: "BKSDA-SU",
  },
  // Riau (Tesso Nilo / Kerumutan)
  {
    key: 107,
    scientificName: "Panthera tigris sumatrae Pocock, 1929",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "MAMMALIA",
    order: "CARNIVORA",
    family: "FELIDAE",
    genus: "Panthera",
    decimalLatitude: -0.1254,
    decimalLongitude: 101.6542,
    year: 2024,
    month: 12,
    day: 22,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "MACHINE_OBSERVATION",
    recordedBy: "WWF Indonesia - Riau Program",
    locality: "Sektor Utara Taman Nasional Tesso Nilo, Pelalawan",
    eventDate: "2024-12-22",
    institutionCode: "WWF-RI",
  },
  {
    key: 108,
    scientificName: "Panthera tigris sumatrae Pocock, 1929",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "MAMMALIA",
    order: "CARNIVORA",
    family: "FELIDAE",
    genus: "Panthera",
    decimalLatitude: -0.3421,
    decimalLongitude: 102.4354,
    year: 2023,
    month: 3,
    day: 30,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "HUMAN_OBSERVATION",
    recordedBy: "Tim Rescue BKSDA Riau",
    locality: "Lansekap Gambut Kerumutan, Indragiri Hulu",
    eventDate: "2023-03-30",
    institutionCode: "BKSDA-RI",
  },
  {
    key: 109,
    scientificName: "Panthera tigris sumatrae Pocock, 1929",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "MAMMALIA",
    order: "CARNIVORA",
    family: "FELIDAE",
    genus: "Panthera",
    decimalLatitude: -0.5602,
    decimalLongitude: 101.3210,
    year: 2018,
    month: 6,
    day: 15,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "MATERIAL_SAMPLE",
    recordedBy: "Universitas Riau Biology Dept",
    locality: "Suaka Margasatwa Bukit Rimbang Baling, Kampar",
    eventDate: "2018-06-15",
    institutionCode: "UR-BIO",
  },
  // Jambi (Kerinci Seblat)
  {
    key: 110,
    scientificName: "Panthera tigris sumatrae Pocock, 1929",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "MAMMALIA",
    order: "CARNIVORA",
    family: "FELIDAE",
    genus: "Panthera",
    decimalLatitude: -2.1245,
    decimalLongitude: 101.4587,
    year: 2025,
    month: 1,
    day: 10,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "HUMAN_OBSERVATION",
    recordedBy: "Fauna & Flora International Jambi",
    locality: "Hutan Lindung Bukit Sanggul, Kerinci",
    eventDate: "2025-01-10",
    institutionCode: "FFI-JAMBI",
  },
  {
    key: 111,
    scientificName: "Panthera tigris sumatrae Pocock, 1929",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "MAMMALIA",
    order: "CARNIVORA",
    family: "FELIDAE",
    genus: "Panthera",
    decimalLatitude: -2.3412,
    decimalLongitude: 101.6789,
    year: 2024,
    month: 9,
    day: 4,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "MACHINE_OBSERVATION",
    recordedBy: "Tiger Protection & Conservation Unit (TPCU)",
    locality: "Taman Nasional Kerinci Seblat Sektor Jambi",
    eventDate: "2024-09-04",
    institutionCode: "TPCU-TNKS",
  },
  // Bengkulu / South Sumatra
  {
    key: 112,
    scientificName: "Panthera tigris sumatrae Pocock, 1929",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "MAMMALIA",
    order: "CARNIVORA",
    family: "FELIDAE",
    genus: "Panthera",
    decimalLatitude: -3.4562,
    decimalLongitude: 102.2412,
    year: 2022,
    month: 7,
    day: 19,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "HUMAN_OBSERVATION",
    recordedBy: "BKSDA Bengkulu Polhut",
    locality: "Taman Nasional Bukit Barisan Selatan, Bengkulu Utara",
    eventDate: "2022-07-19",
    institutionCode: "BKSDA-BKL",
  },
  {
    key: 113,
    scientificName: "Panthera tigris sumatrae Pocock, 1929",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "MAMMALIA",
    order: "CARNIVORA",
    family: "FELIDAE",
    genus: "Panthera",
    decimalLatitude: -4.3210,
    decimalLongitude: 103.1120,
    year: 2021,
    month: 3,
    day: 28,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "MACHINE_OBSERVATION",
    recordedBy: "WCS Bukit Barisan Team",
    locality: "Kawasan Suro, Lahat, Sumatera Selatan",
    eventDate: "2021-03-28",
    institutionCode: "WCS-BBS",
  },
  // Lampung (Bukit Barisan Selatan / Way Kambas)
  {
    key: 114,
    scientificName: "Panthera tigris sumatrae Pocock, 1929",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "MAMMALIA",
    order: "CARNIVORA",
    family: "FELIDAE",
    genus: "Panthera",
    decimalLatitude: -5.1123,
    decimalLongitude: 105.7894,
    year: 2023,
    month: 10,
    day: 11,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "HUMAN_OBSERVATION",
    recordedBy: "Elephant Response Unit (ERU)",
    locality: "Hutan Lindung Rawa Kadut, TN Way Kambas",
    eventDate: "2023-10-11",
    institutionCode: "TNWK",
  },
  {
    key: 115,
    scientificName: "Panthera tigris sumatrae Pocock, 1929",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "MAMMALIA",
    order: "CARNIVORA",
    family: "FELIDAE",
    genus: "Panthera",
    decimalLatitude: -5.5582,
    decimalLongitude: 104.3820,
    year: 2025,
    month: 3,
    day: 2,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "LIVING_SPECIMEN", // Animal sighted by tourist / ranger
    recordedBy: "Pusat Rehabilitasi Harimau Sumatera Tambling (TWNC)",
    locality: "Tambling Wildlife Nature Conservation, Lampung Barat",
    eventDate: "2025-03-02",
    institutionCode: "TWNC",
  },
  {
    key: 116,
    scientificName: "Panthera tigris sumatrae Pocock, 1929",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "MAMMALIA",
    order: "CARNIVORA",
    family: "FELIDAE",
    genus: "Panthera",
    decimalLatitude: -5.2045,
    decimalLongitude: 104.1102,
    year: 2019,
    month: 5,
    day: 14,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "PRESERVED_SPECIMEN",
    recordedBy: "Museum Zoologicum Bogoriense",
    locality: "Liwa, Lampung Barat",
    eventDate: "2019-05-14",
    institutionCode: "MZB",
  }
];


// --- 2. PENYU HIJAU (Chelonia mydas) ---
export const SAMPLE_PENYU_HIJAU: GBIFOccurrence[] = [
  // Banyuwangi (Sukamade)
  {
    key: 201,
    scientificName: "Chelonia mydas (Linnaeus, 1758)",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "REPTILIA",
    order: "TESTUDINES",
    family: "CHELONIIDAE",
    genus: "Chelonia",
    decimalLatitude: -8.5632,
    decimalLongitude: 113.8821,
    year: 2024,
    month: 6,
    day: 15,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "HUMAN_OBSERVATION",
    recordedBy: "Ranger TN Meru Betiri",
    locality: "Pantai Sukamade, Banyuwangi, Jawa Timur",
    eventDate: "2024-06-15",
    institutionCode: "TNMB",
  },
  {
    key: 202,
    scientificName: "Chelonia mydas (Linnaeus, 1758)",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "REPTILIA",
    order: "TESTUDINES",
    family: "CHELONIIDAE",
    genus: "Chelonia",
    decimalLatitude: -8.5684,
    decimalLongitude: 113.8912,
    year: 2025,
    month: 3,
    day: 22,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "MATERIAL_SAMPLE", // Egg count / nest tracking
    recordedBy: "Sukamade Turtle Conservation Center",
    locality: "Sektor Barat Pantai Nesting Sukamade",
    eventDate: "2025-03-22",
    institutionCode: "STCC",
  },
  // West Java (Pangandaran / Pangumbahan)
  {
    key: 203,
    scientificName: "Chelonia mydas (Linnaeus, 1758)",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "REPTILIA",
    order: "TESTUDINES",
    family: "CHELONIIDAE",
    genus: "Chelonia",
    decimalLatitude: -7.3412,
    decimalLongitude: 106.3421,
    year: 2023,
    month: 9,
    day: 10,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "HUMAN_OBSERVATION",
    recordedBy: "Balai Konservasi Pangumbahan",
    locality: "Pantai Pangumbahan, Sukabumi, Jawa Barat",
    eventDate: "2023-09-10",
    institutionCode: "BKP-SUKABUMI",
  },
  // Bali (Serangan / Nusa Penida)
  {
    key: 204,
    scientificName: "Chelonia mydas (Linnaeus, 1758)",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "REPTILIA",
    order: "TESTUDINES",
    family: "CHELONIIDAE",
    genus: "Chelonia",
    decimalLatitude: -8.7212,
    decimalLongitude: 115.2421,
    year: 2024,
    month: 1,
    day: 5,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "LIVING_SPECIMEN", // Released juvenile
    recordedBy: "Turtle Education and Conservation Center (TECC)",
    locality: "Pulau Serangan, Denpasar, Bali",
    eventDate: "2024-01-05",
    institutionCode: "TECC-BALI",
  },
  {
    key: 205,
    scientificName: "Chelonia mydas (Linnaeus, 1758)",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "REPTILIA",
    order: "TESTUDINES",
    family: "CHELONIIDAE",
    genus: "Chelonia",
    decimalLatitude: -8.6812,
    decimalLongitude: 115.4512,
    year: 2022,
    month: 11,
    day: 18,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "MACHINE_OBSERVATION", // Drone / underwater camera
    recordedBy: "Coral Triangle Center (CTC)",
    locality: "Marine Protected Area (MPA) Nusa Penida, Bali",
    eventDate: "2022-11-18",
    institutionCode: "CTC-ID",
  },
  // East Kalimantan (Derawan)
  {
    key: 206,
    scientificName: "Chelonia mydas (Linnaeus, 1758)",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "REPTILIA",
    order: "TESTUDINES",
    family: "CHELONIIDAE",
    genus: "Chelonia",
    decimalLatitude: 2.2212,
    decimalLongitude: 118.2412,
    year: 2024,
    month: 10,
    day: 14,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "HUMAN_OBSERVATION",
    recordedBy: "Yayasan Konservasi Biota Laut Derawan",
    locality: "Pantai Pulau Sangalaki, Kepulauan Derawan",
    eventDate: "2024-10-14",
    institutionCode: "YKBL",
  },
  {
    key: 207,
    scientificName: "Chelonia mydas (Linnaeus, 1758)",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "REPTILIA",
    order: "TESTUDINES",
    family: "CHELONIIDAE",
    genus: "Chelonia",
    decimalLatitude: 2.1542,
    decimalLongitude: 118.1542,
    year: 2020,
    month: 8,
    day: 30,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "PRESERVED_SPECIMEN",
    recordedBy: "Universitas Mulawarman Fishery Dept",
    locality: "Perairan Pulau Derawan, Berau",
    eventDate: "2020-08-30",
    institutionCode: "UNMUL-FISH",
  }
];


// --- 3. BADAK JAWA (Rhinoceros sondaicus) ---
export const SAMPLE_BADAK_JAWA: GBIFOccurrence[] = [
  // Ujung Kulon National Park
  {
    key: 301,
    scientificName: "Rhinoceros sondaicus Desmarest, 1822",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "MAMMALIA",
    order: "PERISSODACTYLA",
    family: "RHINOCEROTIDAE",
    genus: "Rhinoceros",
    decimalLatitude: -6.7412,
    decimalLongitude: 105.3421,
    year: 2025,
    month: 4,
    day: 12,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "MACHINE_OBSERVATION", // Camera trap
    recordedBy: "Balai TN Ujung Kulon (Javan Rhino Study Unit)",
    locality: "Semenanjung Ujung Kulon Sektor Cigenter, Pandeglang, Banten",
    eventDate: "2025-04-12",
    institutionCode: "TNUK-JRSU",
  },
  {
    key: 302,
    scientificName: "Rhinoceros sondaicus Desmarest, 1822",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "MAMMALIA",
    order: "PERISSODACTYLA",
    family: "RHINOCEROTIDAE",
    genus: "Rhinoceros",
    decimalLatitude: -6.8123,
    decimalLongitude: 105.2894,
    year: 2024,
    month: 11,
    day: 8,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "HUMAN_OBSERVATION", // Dung sample / footprint mapping
    recordedBy: "Ranger Patroli Badak Unit VII",
    locality: "Kawasan Hutan Lindung Karang Ranjang, TNUK",
    eventDate: "2024-11-08",
    institutionCode: "TNUK",
  },
  {
    key: 303,
    scientificName: "Rhinoceros sondaicus Desmarest, 1822",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "MAMMALIA",
    order: "PERISSODACTYLA",
    family: "RHINOCEROTIDAE",
    genus: "Rhinoceros",
    decimalLatitude: -6.6542,
    decimalLongitude: 105.4120,
    year: 2023,
    month: 2,
    day: 20,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "MACHINE_OBSERVATION",
    recordedBy: "World Wildlife Fund (WWF) Javan Rhino Project",
    locality: "Rawa Cidaon, Taman Nasional Ujung Kulon",
    eventDate: "2023-02-20",
    institutionCode: "WWF-ID",
  },
  {
    key: 304,
    scientificName: "Rhinoceros sondaicus Desmarest, 1822",
    kingdom: "ANIMALIA",
    phylum: "CHORDATA",
    class: "MAMMALIA",
    order: "PERISSODACTYLA",
    family: "RHINOCEROTIDAE",
    genus: "Rhinoceros",
    decimalLatitude: -6.7891,
    decimalLongitude: 105.3012,
    year: 2021,
    month: 7,
    day: 15,
    country: "Indonesia",
    countryCode: "ID",
    basisOfRecord: "PRESERVED_SPECIMEN", // Historic bone find or plaster cast
    recordedBy: "Museum Zoologicum Bogoriense",
    locality: "Peucang Island Coast, Ujung Kulon",
    eventDate: "2021-07-15",
    institutionCode: "MZB",
  }
];

export const SAMPLE_OPTIONS = [
  {
    id: "harimau",
    label: "🐯 Harimau Sumatra (16 Titik)",
    data: SAMPLE_HARIMAU_SUMATRA,
    description: "Kejadian (occurrences) Panthera tigris sumatrae di sepanjang punggung Bukit Barisan, Sumatra.",
    title: "Harimau Sumatra (Panthera tigris sumatrae)"
  },
  {
    id: "penyu",
    label: "🐢 Penyu Hijau (7 Titik Pantai)",
    data: SAMPLE_PENYU_HIJAU,
    description: "Lokasi pendaratan bertelur Chelonia mydas di Banyuwangi Sukamade, Sukabumi Pangumbahan, & Bali.",
    title: "Penyu Hijau (Chelonia mydas)"
  },
  {
    id: "badak",
    label: "🦏 Badak Jawa (4 Titik Kritis)",
    data: SAMPLE_BADAK_JAWA,
    description: "Observasi intensif Rhinoceros sondaicus menggunakan camera trap di Semenanjung Ujung Kulon.",
    title: "Badak Jawa (Rhinoceros sondaicus)"
  }
];
